name: Daily AI Update

on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 07:00 UTC (08:00 CET) every day
  workflow_dispatch:      # Allows you to click a button to run it manually

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests pandas numpy scikit-learn joblib

      - name: Run AI Engine
        run: python train_ai.py

      - name: Commit and Push Data
        run: |
          git config --global user.name "AI Bot"
          git config --global user.email "bot@football-ai.com"
          git add *.pkl
          git commit -m "🤖 Daily AI Data Update" || exit 0
          git push